improve install method

diff --git a/bin/vpkg b/bin/vpkg
--- a/bin/vpkg
+++ b/bin/vpkg
@@ -19,5 +19,5 @@ if [ "$cmd" == "install" ] ||
 then
   "$cmd" "${@:2}"
 else
-  "$cmd: command not found" && exit 1
+  echo "$cmd: command not found" >&2 && exit 1
 fi
