sourceable

diff --git a/bin/vpkg b/bin/vpkg
--- a/bin/vpkg
+++ b/bin/vpkg
@@ -6,27 +6,31 @@
 # go to own dir
 cd "$(dirname $BASH_SOURCE)"
 
+# args
+cmd="$1"
+shift
+
 # include vpkg function library
 source ../lib/functions
 
 # run
-case "$1" in
+case "$cmd" in
   "install")
-    vpkg-install "${@:2}"
+    vpkg-install "$@"
     ;;
   "uninstall")
-    vpkg-uninstall "${@:2}"
+    vpkg-uninstall "$@"
     ;;
   "link")
-    vpkg-link "${@:2}"
+    vpkg-link "$@"
     ;;
   "unlink")
-    vpkg-unlink "${@:2}"
+    vpkg-unlink "$@"
     ;;
   "-v"|"--version"|"version")
     vpkg-version
     ;;
   *)
-    echo "$1: command not found" >&2 && exit 1
+    echo "$cmd: command not found" >&2 && exit 1
     ;;
 esac
