pass args correctly

diff --git a/bin/vpkg b/bin/vpkg
--- a/bin/vpkg
+++ b/bin/vpkg
@@ -6,31 +6,27 @@
 # go to own dir
 cd "$(dirname $BASH_SOURCE)"
 
-# vars
-cmd="$1"
-args="${@:2}"
-
 # include vpkg function library
 source ../lib/functions
 
 # run
-case "$cmd" in
+case "$1" in
   "install")
-    vpkg-install "$args"
+    vpkg-install "${@:2}"
     ;;
   "uninstall")
-    vpkg-uninstall "$args"
+    vpkg-uninstall "${@:2}"
     ;;
   "link")
-    vpkg-link "$args"
+    vpkg-link "${@:2}"
     ;;
   "unlink")
-    vpkg-unlink "$args"
+    vpkg-unlink "${@:2}"
     ;;
   "-v"|"--version"|"version")
     vpkg-version
     ;;
   *)
-    echo "$cmd: command not found" >&2 && exit 1
+    echo "$1: command not found" >&2 && exit 1
     ;;
 esac
