basic test in place

diff --git a/bin/vpkg b/bin/vpkg
--- a/bin/vpkg
+++ b/bin/vpkg
@@ -3,21 +3,29 @@
 #
 
 # go to own dir
-cd "$(dirname $BASH_SOURCE)" && cd "$(pwd)"
+cd "$(dirname $BASH_SOURCE)"
 
-# get deps
-. ../lib/functions
+# include vpkg function library
+source ../lib/functions
 
-# only run supported commands
-cmd="$1"
-if [ "$cmd" == "install" ] ||
-   [ "$cmd" == "uninstall" ] ||
-   [ "$cmd" == "link" ] ||
-   [ "$cmd" == "unlink" ] ||
-   [ "$cmd" == "use" ] ||
-   [ "$cmd" == "unuse" ]
-then
-  "$cmd" "${@:2}"
-else
-  echo "$cmd: command not found" >&2 && exit 1
-fi
+# run
+case "$1" in
+  "install" )
+    vpkg_install "${@:2}"
+    ;;
+  "uninstall" )
+    vpkg_uninstall "${@:2}"
+    ;;
+  "link" )
+    vpkg_link "${@:2}"
+    ;;
+  "unlink" )
+    vpkg_unlink "${@:2}"
+    ;;
+  "-v"|"--version"|"version" )
+    vpkg_version
+    ;;
+  * )
+    echo "$1: command not found" >&2 && exit 1
+    ;;
+esac
